name:  CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
       gradle-home-cache-cleanup: true

    - name: Run Tests
      run: ./gradlew check

      # Collect Tests Result of failed tests
    - name: Tests Reports
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: tests-result          
        path: ${{ github.workspace }}/build/reports/tests

